"""notifications_log fk set null on delete

Revision ID: d7e73902e716
Revises: b242076acba6
Create Date: 2026-09-30 17:53:35.326132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7e73902e716'
down_revision: Union[str, None] = 'b242076acba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_log_alert_id_fkey'), 'notifications_log', type_='foreignkey')
    op.drop_constraint(op.f('notifications_log_offer_id_fkey'), 'notifications_log', type_='foreignkey')
    op.drop_constraint(op.f('notifications_log_product_id_fkey'), 'notifications_log', type_='foreignkey')
    op.create_foreign_key(None, 'notifications_log', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications_log', 'product_offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications_log', 'alerts', ['alert_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_log_product_id_fkey', 'notifications_log', type_='foreignkey')
    op.drop_constraint('notifications_log_offer_id_fkey', 'notifications_log', type_='foreignkey')
    op.drop_constraint('notifications_log_alert_id_fkey', 'notifications_log', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_log_product_id_fkey'), 'notifications_log', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('notifications_log_offer_id_fkey'), 'notifications_log', 'product_offers', ['offer_id'], ['id'])
    op.create_foreign_key(op.f('notifications_log_alert_id_fkey'), 'notifications_log', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###
